services:
  keycloak-postgresql:
    container_name: keycloak-postgresql
    image: postgres:14.5
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    container_name: keycloak
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:26.1.2
    env_file: .env
    ports:
      - "9090:8080"
    command: start-dev
#    command: start --proxy edge
    networks:
      - keycloak-net

networks:
  keycloak-net:
