services:
  guayabee-postgresql:
    container_name: guayabee-postgresql
    image: postgres:14.5
    env_file: .env.prod
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./postgres-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - guayabee-net

  keycloak:
    container_name: keycloak
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:26.1.2
    env_file: .env.prod
    ports:
      - "9090:8080"
    command: start
    networks:
      - guayabee-net

networks:
  guayabee-net:
