spring:
  application:
    name: gauyabee-core
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://tronxi.ddns.net/auth/realms/guayabee
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/guayabee
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  auth:
    converter:
      resource-id: client-test
      principal-attribute: sub